# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.7.6-browsers`
      - image: continuumio/miniconda3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1.3-dependencies-{{ checksum "environment.yml" }}

      - run:
          name: install dependencies
          command: |
            ENVS=$(conda env list | awk '{print $1}' )
            echo $ENVS
            if ! [[ $ENVS = *"unigram"* ]]; then
              source /opt/conda/etc/profile.d/conda.sh
              conda update -n base -c defaults conda
              conda env create -f environment.yml
              conda activate unigram
              conda install pytorch torchvision cpuonly -c pytorch
              python -m spacy download xx_ent_wiki_sm
            else
              echo "Conda env already installed"
            fi;

      - save_cache:
          key: v1.3-dependencies-{{ checksum "environment.yml" }}
          paths:
            - /opt/conda

      - run:
          name: run linter
          command: |
            source /opt/conda/etc/profile.d/conda.sh
            conda activate unigram
            pylint src/ --rcfile .pylintrc

      # No tests configured yet
      # - run:
      #     name: run tests
      #     command: |
      #       source /opt/conda/etc/profile.d/conda.sh
      #       conda activate unigram
      #       python src/test_circleci.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
